<a href="https://colab.research.google.com/github/karolinazasepa/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro/.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


### Instalacja biblioteki NumPy 


In [1]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


## Podstawy

In [2]:
import numpy as np
np.__version__

'1.21.6'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

#### 1D Array

In [7]:
x = np.array([1, 3])
x

array([1, 3])

In [8]:
print(x)

[1 3]


In [9]:
type(x)

numpy.ndarray

In [11]:
x.ndim #wymiar tablicy

1

In [12]:
x.shape

(2,)

In [13]:
x.size

2

In [15]:
x.dtype # zwraca typ danych

dtype('int64')

In [17]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [18]:
x.dtype

dtype('float64')

#### 2D Array

In [21]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [22]:
x.ndim

2

In [23]:
x.shape

(2, 2)

In [25]:
x = np.array([[1, 2, 4], [4, 2, 1]])
x

array([[1, 2, 4],
       [4, 2, 1]])

In [26]:
x.shape

(2, 3)

#### 3D Array

In [31]:
x = np.array(
    [[[4, 3,  1],
      [3, 1, 2]],
      
      [[4, 1, 3],
       [4, 2, 1]],
     
     [[3, 2, 1],
      [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [32]:
x.ndim

3

In [33]:
x.shape  # liczba tablic, wierszy i kolumn

(3, 2, 3)

### Typ danych

In [34]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [35]:
A = np.array([1.3, 2.0, 3.1])
A.dtype

dtype('float64')

In [36]:
A = np.array([1, 2, 3],  dtype='float')
A.dtype

dtype('float64')

In [38]:
A = np.array([1, 2, 3],  dtype='complex')
A.dtype

dtype('complex128')

In [39]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [40]:
A = np.array([1.3, 2.0, 3.1], dtype='int')
A.dtype

dtype('int64')

In [41]:
A

array([1, 2, 3])

In [43]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [45]:
A = np.array([24, 120, 230], dtype=np.int8) # ograniczenie do liczb 8-bitowych
A.dtype

dtype('int8')

In [46]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

### Tworzenie tablic

In [47]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [48]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [49]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [52]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [54]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [56]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [59]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [60]:
np.linspace(start=0, stop=1, num=10)  #parametr num - ile równo rozłożonych liczb z danego przedziału

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [63]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [66]:
A.reshape((3, -1))  #3  wiersze, liczba kolumn ma być dobrana automatycznie

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [67]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [68]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Operacje na tablicach

In [69]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [70]:
A + B

array([6, 0, 7, 4])

In [77]:
np.add(A,B)

array([6, 0, 7, 4])

In [71]:
A - B

array([0, 2, 1, 0])

In [79]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [72]:
A * B

array([ 9, -1, 12,  4])

In [80]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [73]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [81]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [74]:
A + 3

array([6, 4, 7, 5])

In [75]:
2*A + 3*B

array([15, -1, 17, 10])

In [85]:
X = np.array([[1,3], [-2, 0]])
Y = np.array([[6,0],[-1, 2]])
print(X,'\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [83]:
X * Y #mnoży element po elemencie

array([[6, 0],
       [2, 0]])

In [86]:
np.dot(X, Y) #mnożenie macierzowe

array([[  3,   6],
       [-12,   0]])

In [87]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [88]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [90]:
X @ Y #mnożenie macierzowe

array([[  3,   6],
       [-12,   0]])

### Generowanie liczb pseudolosowych

In [91]:
np.random.seed(0)

In [92]:
np.random.randn() #generowanie liczby losowej z rozkładu normalnego

1.764052345967664

In [93]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [95]:
np.random.randn(10, 4) 

array([[ 0.3869025 , -0.51080514, -1.18063218, -0.02818223],
       [ 0.42833187,  0.06651722,  0.3024719 , -0.63432209],
       [-0.36274117, -0.67246045, -0.35955316, -0.81314628],
       [-1.7262826 ,  0.17742614, -0.40178094, -1.63019835],
       [ 0.46278226, -0.90729836,  0.0519454 ,  0.72909056],
       [ 0.12898291,  1.13940068, -1.23482582,  0.40234164],
       [-0.68481009, -0.87079715, -0.57884966, -0.31155253],
       [ 0.05616534, -1.16514984,  0.90082649,  0.46566244],
       [-1.53624369,  1.48825219,  1.89588918,  1.17877957],
       [-0.17992484, -1.07075262,  1.05445173, -0.40317695]])

In [97]:
np.random.rand() #wartosc z przedziału (0,1), rozkład jednostajny

0.5812728726358587

In [98]:
np.random.rand(10)

array([0.88173536, 0.69253159, 0.72525428, 0.50132438, 0.95608363,
       0.6439902 , 0.42385505, 0.60639321, 0.0191932 , 0.30157482])

In [99]:
np.random.rand(10,3)

array([[0.66017354, 0.29007761, 0.61801543],
       [0.4287687 , 0.13547406, 0.29828233],
       [0.56996491, 0.59087276, 0.57432525],
       [0.65320082, 0.65210327, 0.43141844],
       [0.8965466 , 0.36756187, 0.43586493],
       [0.89192336, 0.80619399, 0.70388858],
       [0.10022689, 0.91948261, 0.7142413 ],
       [0.99884701, 0.1494483 , 0.86812606],
       [0.16249293, 0.61555956, 0.12381998],
       [0.84800823, 0.80731896, 0.56910074]])

In [101]:
np.random.randint(10)

3

In [102]:
np.random.randint(low=10, high=101) #losowa liczba 2-cyfrowa

49

In [103]:
np.random.randint(low=10, high=101, size=10)

array([ 19,  83,  51,  33,  13,  56, 100,  60,  13,  41])

In [104]:
np.random.choice([4, 2, 3, 1]) #losowy element z podanej liczby

2

In [105]:
np.random.choice(['python', 'java','sql'])

'sql'

In [107]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
np.random.shuffle(data)
data

array([8, 9, 7, 3, 2, 5, 4, 6, 1, 0])

### Podstawowe funkcje

In [111]:
np.exp(1)

2.718281828459045

In [112]:
np.sqrt(9)

3.0

In [117]:
np.all([0, 3, 1]) #sprawdza po kolei obiekty, czy zwracają prawdę

False

In [116]:
np.any([0, 0, 0]) #sprawdza, czy jakikolwiek obiekt zwraca prawdę

False

In [118]:
A = np.random.rand(5)
A #prawdopodobieństwo otrzymania poszczególnej klasy dla danej próbki

array([0.34535168, 0.92808129, 0.7044144 , 0.03183893, 0.16469416])

In [119]:
np.argmax(A) #zwraca index

1

In [120]:
A[np.argmax(A)]

0.9280812934655909

In [121]:
np.argmin(A)

3

In [122]:
np.argsort(A) #sortuje rosnąco, zwracając indeksy

array([3, 4, 0, 2, 1])

In [123]:
np.max(A)

0.9280812934655909

In [124]:
np.min(A)

0.03183892953130785

In [125]:
np.mean(A)

0.43487609242304937

In [126]:
np.median(A)

0.3453516806969027

In [127]:
np.std(A)

0.3344709625934017

### Indeksowanie i wycinanie tablic

In [128]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[inx], A[start:stop], A[:stop], A[start:]

In [129]:
A[2]

2

In [130]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [131]:
A[:2]

array([0, 1])

In [133]:
A[[0, 2]]

array([0, 2])

In [134]:
A[-1]

19

In [135]:
A[10:15]

array([10, 11, 12, 13, 14])

In [142]:
A = A.reshape(4,-1)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [144]:
A[1]

array([5, 6, 7, 8, 9])

In [146]:
A[:, 4]  #wycinanie kolumny

array([ 4,  9, 14, 19])

In [147]:
A[1,3] #wycinanie konkretnego elementu

8

In [148]:
A[1:2, 1:4]

array([[6, 7, 8]])

In [151]:
A[1,2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### Iteracja po tablicach

In [153]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [154]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [156]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [ ]:
for item in A.flat: #splaszczenie tablicy,by iterować po każdym elemencie
  print(item)

### Zmiana rozmiaru tablic

In [159]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [160]:
A.shape

(4, 5)

In [161]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [163]:
A.ravel()  #spłasczenie danych

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [165]:
A.T #transponowanie tablicy

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### Maski logiczne

In [168]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [169]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [171]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [177]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [179]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [180]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [181]:
A[np.bitwise_or(A < -5, A > 5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])